config/routes.rb
Rails.application.routes.draw do
  get 'static_pages/home'

  get 'pdf_pages/show'

  root 'static_pages#home'

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pdf_pages_controller.rb
class PdfPagesController < ApplicationController
  def show
    respond_to do |format|
      format.html
      format.pdf do
        render  :pdf => 'This is the PDF Name',
                :template => 'pdf_pages/show.html.erb'
      end
    end
  end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pdf_pages_helper.rb
module PdfPagesHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>HerokuPdfs</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/pdf_pages/show.html.erb
<meta charset='utf-8' />
<%= wicked_pdf_stylesheet_link_tag "pdf" %>


Boom!  We have ourselves a pdf
<br>
<br>
<div class="custom_font">And this is the custom font</div>

app/views/static_pages/home.html.erb
<div class="home_title">This is the home page for the heroku pdf test</div>
<br>

<%= link_to "PDF - html page", pdf_pages_show_path %>
<br>
<%= link_to "PDF - new tab", pdf_pages_show_path(format: 'pdf'), target: "_blank" %>